

typeset -U path cdpath fpath manpath

for profile in ${(z)NIX_PROFILES}; do
  fpath+=($profile/share/zsh/site-functions $profile/share/zsh/$ZSH_VERSION/functions $profile/share/zsh/vendor-completions)
done

HELPDIR="/nix/store/azf64cfahr0215gildbdksf6lmjghnyg-zsh-5.9/share/zsh/$ZSH_VERSION/help"





# Oh-My-Zsh/Prezto calls compinit during initialization,
# calling it twice causes slight start up slowdown
# as all $fpath entries will be traversed again.



# oh-my-zsh extra settings for plugins

# oh-my-zsh configuration generated by NixOS
plugins=(git zoxide z)

ZSH_THEME="funky"
source $ZSH/oh-my-zsh.sh





# History options should be set in .zshrc and after oh-my-zsh sourcing.
# See https://github.com/nix-community/home-manager/issues/177.
HISTSIZE="10000"
SAVEHIST="10000"

HISTFILE="$HOME/.zsh_history"
mkdir -p "$(dirname "$HISTFILE")"

setopt HIST_FCNTL_LOCK
setopt HIST_IGNORE_DUPS
unsetopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
unsetopt HIST_EXPIRE_DUPS_FIRST
setopt SHARE_HISTORY
unsetopt EXTENDED_HISTORY




# Aliases
alias -- 'cleangens'='sudo nix-collect-garbage -d'
alias -- 'copyfiles'='copynix && copyhypr && copywaybar'
alias -- 'copyhypr'='cp ~/.config/hypr/* ~/Downloads/dotties/hypr'
alias -- 'copynix'='cp /etc/nixos/* ~/Downloads/dotties/nixos'
alias -- 'copywaybar'='cp ~/.config/waybar/* ~/Downloads/dotties/waybar'
alias -- 'flakeconf'='sudo nvim /etc/nixos/flake.nix'
alias -- 'genlist'='sudo nix-env --list-generations -p /nix/var/nix/profiles/system'
alias -- 'homeconf'='sudo nvim /etc/nixos/home.nix'
alias -- 'homerb'='home-manager switch --flake /etc/nixos#liz'
alias -- 'hyprconf'='nvim ~/.config/hypr/hyprland.conf'
alias -- 'nixcg'='nix-collect-garbage'
alias -- 'nixconf'='sudo nvim /etc/nixos/configuration.nix'
alias -- 'nixrb'='sudo nixos-rebuild switch --flake /etc/nixos#nixos'
alias -- 'upgrade'='sudo nixos-rebuild switch --upgrade'
alias -- 'v'='nvim'

# Named Directory Hashes




